### ISSUE TITLE
notivue breaks with nuxt v3.13.2

### ISSUE THREAD

**Issue by peralta** [smastrom/notivue#69] opened 2024-09-16 20:46 UTC
Error shows when running in dev mode (and not on a statically generated build with `nuxt generate`):
```
Cannot destructure property 'isRunning' of 'useNotivueInstance(...)' as it is undefined.
```

Used to work on v3.13.1. Can easily be reproduced by upgrading manually the Stackblitz playground.

**Comment by smastrom** [comment] 2024-09-16 23:09
Hi @peralta, thank you for making me aware of that. I don't know why this is happening, but I assume that there is some kind of issue with Vue's `inject` on the latest Nuxt version.

`useNotivueInstance` is nothing than a wrapper function around `inject` that returns an object with the same shape both on the server and the client, therefore it should never be `undefined`.

Probably, there is some mismatch between the `provide` counterpart which might called after `inject` or not called at all. But I reallty have no clue as I don't maintain the framework.

I tried to dive into that in order to find a workaround but unforunately, as you can see from the screenshot below, the playground works perfectly on the latest version of Nuxt.
 
<img width="1792" alt="Screenshot 2024-09-17 alle 00 40 04" src="https://github.com/user-attachments/assets/b5f45a35-bd74-4081-8ec9-1e999fe01ff5">

**Comment by smastrom** [comment] 2024-09-16 23:09
Hi @peralta, thank you for making me aware of that. I don't know why this is happening, but I assume that there is some kind of issue with Vue's `inject` on the latest Nuxt version.

`useNotivueInstance` is nothing than a wrapper function around `inject` that returns an object with the same shape both on the server and the client, therefore it should never be `undefined`.

Probably, there is some mismatch between the `provide` counterpart which might called after `inject` or not called at all. But I reallty have no clue as I don't maintain the framework.

I tried to dive into that in order to find a workaround but unforunately, as you can see from the screenshot below, the playground works perfectly on the latest version of Nuxt.
 
<img width="1792" alt="Screenshot 2024-09-17 alle 00 40 04" src="https://github.com/user-attachments/assets/b5f45a35-bd74-4081-8ec9-1e999fe01ff5">

**Comment by smastrom** [comment] 2024-09-16 23:12
Hi @peralta, thank you for making me aware of that. I don't know why this is happening, but I assume that there is some kind of issue with Vue's `inject` on the latest Nuxt version.

`useNotivueInstance` is nothing than a wrapper function around `inject` that returns an object with the same shape both on the server and the client, therefore it should never be `undefined`.

Probably, there is some mismatch between the `provide` counterpart which might called after `inject` or not called at all. Or maybe there is some issue with its injection key / symbol. I really have no clue as I don't maintain the framework.

I tried to dive into that in order to find a workaround but unforunately, as you can see from the screenshot below, the playground works perfectly on the latest version of Nuxt.
 
<img width="1792" alt="Screenshot 2024-09-17 alle 00 40 04" src="https://github.com/user-attachments/assets/b5f45a35-bd74-4081-8ec9-1e999fe01ff5">

**Comment by peralta** [comment] 2024-09-17 05:19
Hi @smastrom, thanks for your quick reply.
Here is how to reproduce:

1. Open the stackblitz nuxt example that you have linked in the project README: https://stackblitz.com/edit/nuxt-starter-fnhcmx?file=pages%2Findex.vue
2. Stop the server and run `nuxi upgrade -f`, which brings nuxt to v3.12.2
3. Start the server again with `nuxt dev`. The example site is now broken with the message https://github.com/smastrom/notivue/issues/69#issue-2529462804

Thanks,

**Comment by BayBreezy** [comment] 2024-09-17 08:12
Came here because I am experiencing the sam error in a nuxt app I updated just now.
The error is only in dev mode. 
After building the app, the error was nowhere to be found 🤷🏽‍♂️

**Comment by peralta** [comment] 2024-09-17 15:09
Fixed on nuxt side: https://github.com/nuxt/nuxt/pull/29036

**Comment by LBC000** [comment] 2024-09-22 12:31
<img width="1117" alt="image" src="https://github.com/user-attachments/assets/5e6440a6-cece-4014-a660-1175e691519c">
I also encountered the same problem

**Comment by smastrom** [comment] 2024-09-22 13:21
Hi @LBC000, as already explained in the replies of this thread, this is not a Notivue issue.

Various Vue libraries have been affected by this regression introduced in Nuxt v3.13.2.

According to the Nuxt repo, they already merged a [PR](https://github.com/nuxt/nuxt/pull/29036) to fix it but we must wait the release of Nuxt [v3.14.0](https://github.com/nuxt/nuxt/pull/29077) in order to leverage it.

Until then, I suggest to pin the `nuxt` version in your `package.json` to `3.13.1`.

```diff
-  "nuxt": "^3.13.1",
+  "nuxt": "3.13.1",
```

```diff
-  "nuxt": "^3.13.2",
+  "nuxt": "3.13.1",
```
 
I'm going to close this issue as there's nothing we can do about that more than waiting.

**Closed by smastrom** 2024-09-22 13:21 UTC
Labels: invalid, nuxt

**Comment by tinegaCollins** [comment] 2024-10-22 19:48
re open this issue cause it is still not fixed

**Comment by tinegaCollins** [comment] 2024-10-22 19:49
@danielroe can you please check on this

**Comment by danielroe** [comment] 2024-10-22 22:12
this will be resolved in next nuxt release

**Comment by tinegaCollins** [comment] 2024-10-23 07:08
Thank you
